name: healthcare_etl
version: 1.0.0
config-version: 2

profile: healthcare_etl

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  healthcare_etl:

    # -----------------------------------------
    # BRONZE — RAW DATA (from seeds)
    # -----------------------------------------
    bronze:
      +schema: bronze
      +materialized: table

      procedures_raw:
      organizations_raw:
      patients_raw:
      encounters_raw:
      payers_raw:

    # -----------------------------------------
    # SILVER — CLEANED, TYPED, CONSISTENT
    # -----------------------------------------
    silver:
      +schema: silver
      +materialized: view

      stg_encounters:
      stg_organizations:
      stg_patients:
      stg_payers:
      stg_procedures:

    # -----------------------------------------
    # GOLD — BUSINESS MODELS
    # -----------------------------------------
    gold:
      +schema: gold
      +materialized: view

      payer_ranking:
      prodecure_cost: 
      top5_patients:
      top5_procedures_daily_cost:    

seeds:
  healthcare_etl:
    +schema: bronze
    +quote_columns: false

    procedures:
    patients:
    encounters:
    payers:
