version: 2

models:
  - name: stg_encounters
    description: "Cleaned encounter-level data."
    columns:
      - name: Id
        tests:
          - not_null
          - unique
      - name: PATIENT
        tests:
          - not_null
  - name: stg_organizations
    description: "Cleaned organization data."
    columns:
      - name: Id
        tests:
          - not_null
          - unique
      - name: NAME
        tests:
          - not_null
  - name: stg_patients
    description: "Cleaned patient demographic data."
    columns:
      - name: Id
        tests:
          - not_null
          - unique
      - name: BIRTHDATE
        tests:
            - not_null
      - name: FIRST
        tests:
            - not_null
      - name: LAST
        tests:
            - not_null        
      - name: GENDER
        tests:
          - accepted_values:
              values: ['male', 'female', 'other']
  - name: stg_payers
    description: "Cleaned payer information."
    columns:
      - name: Id
        tests:
          - not_null
          - unique
      - name: NAME
        tests:
          - not_null
  - name: stg_procedures
    description: "Cleaned and enriched procedures data with duration and date parts."
    columns:
      - name: PATIENT
        tests:
          - not_null
      - name: ENCOUNTER
        tests:
          - not_null
      - name: CODE
        tests:
          - not_null
      - name: BASE_COST
        tests:
          - not_null
          - greater_than: {value: 0}
      - name: DURATION_SECONDS
        tests:
          - not_null
          - greater_than: {value: 0}
      - name: YEAR
        tests:
          - not_null
      - name: MONTH_NUMBER
        tests:
          - not_null
          - between:
              min_value: 1
              max_value: 12
      - name: WEEK_NUMBER
        tests:
          - not_null
